name: Build MCEconomy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Added permissions to allow publishing to GitHub Packages
    permissions:
      contents: read
      packages: write

    steps:
      # 1. Check out the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Set up Java 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          # This helper can also handle server settings for maven
          server-id: github 

      # 3. Grant execute permission
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. Build with Gradle
      - name: Build and Publish with Gradle
        run: ./gradlew clean build shadowJar publish
        env:
          BUILD_NUMBER: ${{ github.run_number }}
          # Use your custom secrets here
          USER_GITHUB_NAME: ${{ github.actor }}
          USER_GITHUB_TOKEN: ${{ secrets.AGENT_TOKEN }}

      # 5. Save the JARs
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MCEngine-Build-${{ github.run_number }}
          path: |
            **/build/libs/*-all.jar
            **/build/libs/*.jar
            !**/build/libs/*-plain.jar
          retention-days: 1
